# 服务器端口
server:
  port: 6024

spring:
  kafka:
    bootstrap-servers: 192.168.10.109:9092
    consumer:
      group_id: vcasw-data-dev1

  rabbitmq:
      dga:
        host: 192.168.10.109
        port: 5672
        username: admin
        password: citms